spring.application.name=gestao-academia

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/academia_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:8zPqW3nRtX2yLv5mK9jA1b6sD4fG7hJ0k9mN2bV4cX5zL8pQ1wE3rT5yU7iO9p}